language: python
script: python -m unittest discover
install: pip3 install generalvector
python: 3.8

jobs:
  include:
    - os: linux
    - os: osx
      osx_image: xcode11.6
      env: TOXENV=py38
      language: generic
      before_install:
        - python --version
        - python3 --version
        - python@3.8 --version
        - brew info python@3.8
        - brew upgrade python@3.8
        - python --version
        - python3 --version
      script: python3 -m unittest discover
      before_cache:
      - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
        # Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
        # Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
      - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python --version
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH



