language: python
install: pip3 install generalvector
script: python -m unittest discover
python: 3.8

jobs:
  include:

    - name: "Python 3.8.0 on Linux Xenial"
      os: linux
      dist: xenial
      before_install: python --version

    - name: "Python 3.8.0 on Linux Bionic"
      os: linux
      dist: bionic
      before_install: python --version

    - name: "Python 3.8.3 on MacOS 11.6"
      os: osx
      osx_image: xcode11.6
      language: shell
      before_install: /usr/local/opt/python@3.8/bin/python3 --version
      install: /usr/local/opt/python@3.8/bin/python3 -m pip install generalvector
      script: /usr/local/opt/python@3.8/bin/python3 -m unittest discover

    - name: "Python 3.8.3 on MacOS 12"
      os: osx
      osx_image: xcode12
      language: shell
      before_install: /usr/local/opt/python@3.8/bin/python3 --version
      install: /usr/local/opt/python@3.8/bin/python3 -m pip install generalvector
      script: /usr/local/opt/python@3.8/bin/python3 -m unittest discover

    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - systeminfo
        - choco install python --version 3.8.0
        - python --version
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH



