language: python
script: python -m unittest discover
install: pip3 install generalvector
python: 3.8

jobs:
  include:
    - os: linux
    - os: osx
      osx_image: xcode11.6
      language: generic
      before_install:
        - brew unlink python
        - brew link --force python@3.8
        - python --version
        - export PATH="/usr/local/opt/python@3.8/bin:$PATH"
        - python --version
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python --version
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH



