
name: UnitTest and Merge

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  unittest:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          python-version: [3.7, 3.8]
          os: [ubuntu-latest, windows-latest, macos-latest]

      steps:
        - uses: actions/checkout@v2

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .

        - name: Run UnitTests
          run: |
            python -m unittest discover

  merge:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      uses: tukasz/direct-merge-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: deploy
        target-branch: master










































